### ISSUE TITLE
event planifiés count

### ISSUE THREAD

**Issue by laetitiamassa** [shcyiza/oac_agenda#3]
exemple avec un loop : 

def global_funding
    global_funding = 0
    following_projects.each do |project|
      global_funding += project.funding.to_i
    end
    global_funding
  end

**Comment by laetitiamassa** [comment]
ici il faut ajouter += 1 au lieu de += ed.etc

**Comment by shcyiza** [comment]
j'ai peu le faire comme ca:
  <% events_that_day = 0 %>
  <% @events.each do |event| %>
    <% if event.day.include?(jour) == true %>
      <% events_that_day  += 1 %>
    <% end %>
  <% end %>

<%= events_that_day %>
